### ISSUE TITLE
Jenkins: Armada Plugin

### ISSUE THREAD

**Issue by dave-gantenbein** [armadaproject/jenkins-plugin#1]
Initial design spike

**Comment by mladjan-gadzic** [comment]
these are all the specs that i could gather right now https://gist.github.com/mladjan-gadzic/7e447390fa66dc8acd256b60744c2b74

**Comment by mladjan-gadzic** [comment]
working mvp can be found here https://github.com/armadaproject/jenkins-plugin/tree/grpc
